### ISSUE TITLE
Reorder kableExtra calls in `fpr_table_bcfp_html`

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fpr#87]
Need to reorder kableExtra calls in `fpr_table_bcfp_html` so that `kableExtra::add_footnote`  is called after `kableExtra::kable_styling`, as seen here https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/issues/41.

error message is:
```
Error in `[.data.frame`(ids.ops, , notation) : undefined columns selected
```
and swapping the order of the calls fixed it. 

This issue might need some more investigating because it looks like this is not an issue in https://github.com/NewGraphEnvironment/fpr/blob/main/R/tables.R#L216C1-L224C2.

**Comment by NewGraphEnvironment** [comment]
That **was** was also an issue in `fpr_table_cv_html`  .  We should be able to build those tables that link in the interactive map now (that's what those functions have been used for). This is wonderful - as those links have been dead in reports since 2020 and can now be updated.

![image](https://github.com/NewGraphEnvironment/fpr/assets/46538103/ab2640bf-6f00-4a14-8990-3c8553590d2a)

**Comment by NewGraphEnvironment** [comment]
yup.  That was the issue.  Needed a couple other tweaks to `fpr_table_bcfp_html` (remove redundant call to `fpr_kable`) but `fpr_table_cv_html` went off without a hitch with just that one mod.

Before after shown

![image](https://github.com/NewGraphEnvironment/fpr/assets/46538103/f726d7d4-a4b2-4bed-b27f-85fef7f2fcac)
